filter:
  paths: [src/*]
  excluded_paths: [tests/*]
tools:
  php_analyzer: true
  php_sim: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_changetracking: true
  php_mess_detector:
    enabled: true
    config:
      ruleset:              ~
      code_size_rules:
        cyclomatic_complexity: true
        npath_complexity: true
        excessive_method_length: true
        excessive_class_length: true
        excessive_parameter_list: true
        excessive_public_count: true
        too_many_fields: true
        too_many_methods: true
        excessive_class_complexity: true
      design_rules:
        exit_expression: true
        eval_expression: true
        goto_statement: true
        number_of_class_children: true
        depth_of_inheritance: true
        coupling_between_objects: true
      unused_code_rules:
        unused_private_field: true
        unused_local_variable: true
        unused_private_method: true
        unused_formal_parameter: true
      naming_rules:
        short_variable:
          minimum: 3
        long_variable:
          maximum: 20
        short_method:
          minimum: 3
        constructor_conflict: true
        constant_naming: true
        boolean_method_name: true
      controversial_rules:
        superglobals: true
        camel_case_class_name: true
        camel_case_property_name: true
        camel_case_method_name: true
        camel_case_parameter_name: true
        camel_case_variable_name: true
checks:
  php:
    code_rating: true

build:
  dependencies:
    before:
    - composer self-update
  environment:
    variables:
      TEST_POSTGRES_DSN: 'pgsql://scrutinizer:scrutinizer@localhost:5432/test'
  nodes:
    node-that-needs-postgresql:
      dependencies:
        before:
        - psql -c "CREATE DATABASE test WITH OWNER = scrutinizer ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' TEMPLATE template0"
    coverage:
      tests:
        override:
        - command: ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml
          coverage:
            file: build/logs/clover.xml
            format: clover
    analysis:
      project_setup:
        override: true
      tests:
        override:
        - php-scrutinizer-run --enable-security-analysis

