language: php

php:
  - 7.2
  - 7.3

services:
  - postgresql
  - rabbitmq

cache:
  directories:
    - $HOME/.cache/composer

before_script:
  - mkdir -p build/logs
  - psql -c 'CREATE DATABASE test;' -U postgres

install:
  - travis_retry composer install --no-interaction --no-suggest
  - travis_retry wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - travis_retry wget -c -nc --retry-connrefused --tries=0 https://scrutinizer-ci.com/ocular.phar
  - chmod +x ocular.phar php-coveralls.phar

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - travis_retry php php-coveralls.phar -v
  - bash <(curl -s https://codecov.io/bash)
