language: php

php:
- 7.2
- 7.3

install:

- travis_retry composer install --no-interaction --no-suggest
- wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar -O coveralls.phar
- chmod +x coveralls.phar
- wget https://scrutinizer-ci.com/ocular.phar
- chmod +x ocular.phar
- php coveralls.phar --version

before_script:
- mkdir -p build/logs
- ls -al
- psql -c 'CREATE DATABASE test;' -U postgres

script:
- ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
- travis_retry php coveralls.phar -v
- bash <(curl -s https://codecov.io/bash)
- travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

cache:
  directories:
  - vendor
  - $HOME/.cache/composer

services:
- postgresql
- rabbitmq

